# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60384cc811311ab9d8fbe68a1a6db9bae32aab61348a86c8cfe7e52e73fa31ba8f573a826f384b0148b23c039498d50af2732dee4c48078d29aa4f3b97375a0c

test:
  secret_key_base: dd53d13cb0dd0e5e305c444d61d4a4c30de0f3394306632230cfa9506fd30e733de5570d8c25d1bf8b165038fc62eaa4be51faa1fd9d2e867a1c7ccfe5b1be7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
