# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c8735e8eef8d71da0fb9360758eb13b22da863a1b54048853330f86e1a5311356655a67801b4f175307534bef4687cacd3ef43091ac1d424c7610945df4ffa0

test:
  secret_key_base: 28251bdc9c21e69c7efa11dea4d98b109f7795cf53ed47bfe911726c3529e862f122cf9172506d499fbd5bd35f760c66fa9ac1ba19e18fd3d3e3568ee0754670

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
